/* eslint-disable jest/no-standalone-expect */

import { Resolver } from '..'
import { describeVariants } from '../resolver/__tests__/testlib'

describeVariants(
	'regression',
	(test, fixTimeline, getCache) => {
		test('#1', () => {
			const timeline = fixTimeline(TL)
			const date = 1741053081557

			const resolved = Resolver.resolveTimeline(timeline, { cache: getCache(), time: date })

			const state0 = Resolver.getState(resolved, date)
			expect(state0.time).toEqual(date)
			expect(state0.layers).toMatchObject({
				vmix_faux_preview: {
					content: { layers: { '1': { input: '6' } } },
				},
			})
		})
	},
	{
		normal: true,
		reversed: true,
		cache: true,
	}
)

const TL = [
	{
		id: 'gbuxnDkvscizjDOHWXC2aX35eos_',
		enable: { while: '1' },
		layer: 'vmix_vegg_me',
		content: { deviceType: 'VMIX', type: 'PROGRAM', input: 43 },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'uskvjTu1JsRePLx0vbedbVHCyyA_',
		enable: { while: '1' },
		layer: 'vmix_me_program',
		content: { deviceType: 'VMIX', type: 'PROGRAM', input: 46 },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'xRFY6m_Jg9VCk_egZrdiLkNewVc_',
		enable: { start: 0 },
		layer: 'vmix_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'SDvbH3f1ggieFehQyhwTyOjz_Sk_',
		enable: { start: 0 },
		layer: 'vmix_mv_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: '7oK5p8JjaFoOysG16wCkXYcleAQ_',
		enable: { while: '1' },
		layer: 'vmix_dve_bg',
		content: { deviceType: 'VMIX', type: 'INPUT', loop: true, playing: true },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'WNuFmhmuRYhvZPce6LGPdvPiUbE_',
		enable: { while: '1' },
		layer: 'vmix_overlay_graphics_input',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			url: 'about:blank',
			$references: { url: { datastoreKey: 'overdog0_output_url', overwrite: false } },
		},
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: '2_yhidKdvRs3mIb2AJqzndBlcnQ_',
		enable: { while: '1' },
		layer: 'vmix_overlay_graphics',
		content: { deviceType: 'VMIX', type: 'OVERLAY', input: 18 },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'T7lg735NryDF9ojCG_KzKGF5K2c_',
		enable: { while: '1' },
		layer: 'vmix_dve_1',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: 31 },
				'2': { input: 45 },
				'3': { input: 45 },
				'4': { input: 45 },
				'5': { input: 45 },
			},
		},
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'PfOeLatcKbdyTiBUGhPciu8Vfos_',
		enable: { while: '1' },
		layer: 'vmix_dve_2',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: 31 },
				'2': { input: 45 },
				'3': { input: 45 },
				'4': { input: 45 },
				'5': { input: 45 },
			},
		},
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: '3rmXhyQ75kdnAJSmSfolptenJ_g_',
		priority: 1,
		enable: { start: 0 },
		layer: 'vmix_mv_1',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': {
					panX: -0.5529171,
					panY: 0.5512499,
					zoom: 0.4470833,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 44,
				},
				'2': {
					panX: -0.000001072884,
					panY: 5.364418e-7,
					zoom: 0.9999994,
					cropLeft: 0.5674,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 40,
				},
				'3': {
					panX: -0.7916667,
					panY: -0.1342592,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 2,
				},
				'4': {
					panX: -0.3541667,
					panY: -0.1342592,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 3,
				},
				'5': {
					panX: 0.07604141,
					panY: -0.1342592,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 4,
				},
				'6': {
					panX: 0.5208333,
					panY: -0.1342592,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 5,
				},
				'7': {
					panX: -0.7916667,
					panY: -0.6805552,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 1,
				},
				'8': {
					panX: -0.3541667,
					panY: -0.6805555,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 10,
				},
				'9': {
					panX: 0.07604141,
					panY: -0.6805551,
					zoom: 0.2083333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 6,
				},
				'10': {
					panX: 0.520833,
					panY: -0.680555,
					zoom: 0.208333,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 7,
				},
			},
		},
		objectType: 'rundown',
	},
	{
		id: 'IVy_ebMksB32OukUC22rhmT_wS8_',
		priority: 1,
		enable: { start: 0 },
		layer: 'vmix_mv_2',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': {
					panX: 0.5241667,
					panY: 0.5512964,
					zoom: 0.4470834,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 43,
				},
				'2': {
					panX: 0.8802071,
					panY: -0.08180565,
					zoom: 0.1197914,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 59,
				},
				'3': {
					panX: 0.8802083,
					panY: -0.4010416,
					zoom: 0.1197915,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 60,
				},
				'4': {
					panX: 0.8802073,
					panY: -0.640625,
					zoom: 0.1197916,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 61,
				},
				'5': {
					panX: 0.8802073,
					panY: -0.8802083,
					zoom: 0.1197916,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
					input: 62,
				},
			},
		},
		objectType: 'rundown',
	},
	{
		id: 'vtSoUqZAmXRpcPpamc0GE2H62c8_',
		priority: 0,
		enable: { start: 0 },
		layer: 'vmix_overlay_wipe_input',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			listFilePaths: ['N:\\\\wipe_gfx\\\\NEWS_SignaturWipe_v01.mov', 'N:\\\\wipe_gfx\\\\SPORTS_SignaturWipe.mov'],
		},
		objectType: 'rundown',
	},
	{
		id: 'WxT1fRR6jHKIn9FyIibQWWIpXxo_',
		enable: { while: '1' },
		layer: 'vmix_audio_master',
		content: { deviceType: 'VMIX', type: 'AUDIO_BUS', muted: false },
		priority: 0,
		objectType: 'rundown',
	},
	{
		id: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U__status',
		objectType: 'rundown',
		enable: { while: 1 },
		layer: 'rundown_status',
		content: { deviceType: 'ABSTRACT' },
		classes: ['rundown_active'],
		priority: 0,
	},
	{
		id: 'part_group_EQg6irXwHuc2TMyqC',
		objectType: 'rundown',
		enable: { start: 1740825479332, end: '#part_group_2KDYWrf2pcRxMfag8.start + 0' },
		priority: -1,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'piece_group_control_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'dve_composition',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: 'EQg6irXwHuc2TMyqC',
						pieceInstanceId: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['previous_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_',
				},
			},
			{
				id: 'piece_group_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_0BJQfI4Qnc0nZk5WWZKuSmjDHOc_',
						priority: 1,
						enable: { start: 0 },
						layer: 'vmix_me_program',
						content: { deviceType: 'VMIX', type: 'PROGRAM', input: 46 },
						keyframes: [
							{
								id: '0BJQfI4Qnc0nZk5WWZKuSmjDHOc__keyframe_dve_2_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_0BJQfI4Qnc0nZk5WWZKuSmjDHOc_',
								enable: { while: '1' },
								disabled: false,
								content: { input: 28 },
								preserveForLookahead: true,
								abSession: { poolName: 'dve', playerIndex: 1 },
							},
						],
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						objectType: 'rundown',
						originalId: '0BJQfI4Qnc0nZk5WWZKuSmjDHOc_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_ok4WhtWboVqBsmRaFK0WLIIlXCk_',
						enable: { start: 0 },
						layer: 'vmix_faux_preview',
						content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
						keyframes: [
							{
								id: 'ok4WhtWboVqBsmRaFK0WLIIlXCk__keyframe_dve_2_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_ok4WhtWboVqBsmRaFK0WLIIlXCk_',
								enable: { while: '1' },
								disabled: false,
								content: { layers: { '1': { input: 28 } } },
								preserveForLookahead: true,
								abSession: { poolName: 'dve', playerIndex: 1 },
							},
						],
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						priority: 0,
						objectType: 'rundown',
						originalId: 'ok4WhtWboVqBsmRaFK0WLIIlXCk_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_cE0QdXpwBTedTj1hbGz_JWdw7EE_',
						enable: { start: 0 },
						layer: 'vmix_mv_faux_preview',
						content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
						keyframes: [
							{
								id: 'cE0QdXpwBTedTj1hbGz_JWdw7EE__keyframe_dve_2_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_cE0QdXpwBTedTj1hbGz_JWdw7EE_',
								enable: { while: '1' },
								disabled: false,
								content: { layers: { '1': { input: 28 } } },
								preserveForLookahead: true,
								abSession: { poolName: 'dve', playerIndex: 1 },
							},
						],
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						priority: 0,
						objectType: 'rundown',
						originalId: 'cE0QdXpwBTedTj1hbGz_JWdw7EE_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_F669L65bjFMMWnOtYlkSOXXmjN4_',
						priority: 1,
						enable: { start: 0 },
						layer: 'vmix_dve_2',
						content: {
							deviceType: 'VMIX',
							type: 'INPUT',
							layers: {
								'1': {
									input: '31',
									panX: 0,
									panY: 0,
									zoom: 1,
									cropLeft: 0,
									cropTop: 0,
									cropRight: 1,
									cropBottom: 1,
								},
								'2': {
									input: 2,
									panX: -0.673,
									panY: 0,
									zoom: 0.4,
									cropLeft: 0.1042,
									cropTop: 0,
									cropRight: 0.8958,
									cropBottom: 1,
								},
								'3': {
									input: 1,
									panX: 0,
									panY: 0,
									zoom: 0.4,
									cropLeft: 0.1042,
									cropTop: 0,
									cropRight: 0.8958,
									cropBottom: 1,
								},
								'4': {
									input: 62,
									panX: 0.673,
									panY: 0,
									zoom: 0.4,
									cropLeft: 0.1042,
									cropTop: 0,
									cropRight: 0.8958,
									cropBottom: 1,
								},
							},
						},
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						objectType: 'rundown',
						originalId: 'F669L65bjFMMWnOtYlkSOXXmjN4_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sM5pn9UiPZf6kWNwDKXLKWckdaQ_',
						enable: { while: '1' },
						layer: 'vmix_dve_labels_1',
						priority: 1,
						content: { type: 'INPUT', deviceType: 'VMIX' },
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						keyframes: [
							{
								id: 'sM5pn9UiPZf6kWNwDKXLKWckdaQ__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sM5pn9UiPZf6kWNwDKXLKWckdaQ_',
								enable: { while: '1' },
								disabled: false,
								abSession: { poolName: 'dve', playerIndex: 1 },
								content: { layers: {} },
								preserveForLookahead: true,
							},
						],
						objectType: 'rundown',
						originalId: 'sM5pn9UiPZf6kWNwDKXLKWckdaQ_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sWPFgU5TaBJMk4qIgp4YcxM4guo_',
						enable: { while: '1' },
						layer: 'vmix_dve_labels_1',
						priority: 1,
						content: { type: 'INPUT', deviceType: 'VMIX' },
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						keyframes: [
							{
								id: 'sWPFgU5TaBJMk4qIgp4YcxM4guo__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sWPFgU5TaBJMk4qIgp4YcxM4guo_',
								enable: { while: '1' },
								disabled: false,
								abSession: { poolName: 'dve', playerIndex: 1 },
								content: { layers: {} },
								preserveForLookahead: true,
							},
						],
						objectType: 'rundown',
						originalId: 'sWPFgU5TaBJMk4qIgp4YcxM4guo_',
					},
					{
						id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_j9xIsiJjovQ4n2Z2BHVpzJZJDL4_',
						enable: { while: '1' },
						layer: 'vmix_dve_labels_1',
						priority: 1,
						content: { type: 'INPUT', deviceType: 'VMIX' },
						abSessions: [{ poolName: 'dve', sessionName: 'Trippel' }],
						keyframes: [
							{
								id: 'j9xIsiJjovQ4n2Z2BHVpzJZJDL4__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_j9xIsiJjovQ4n2Z2BHVpzJZJDL4_',
								enable: { while: '1' },
								disabled: false,
								abSession: { poolName: 'dve', playerIndex: 1 },
								content: { layers: {} },
								preserveForLookahead: true,
							},
						],
						objectType: 'rundown',
						originalId: 'j9xIsiJjovQ4n2Z2BHVpzJZJDL4_',
					},
				],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_.start - 0',
					end: '#piece_group_control_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_',
				},
				priority: 0,
			},
			{
				id: 'piece_group_control_EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'dve_audio',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: 'EQg6irXwHuc2TMyqC',
						pieceInstanceId: 'EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['previous_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: 'EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_',
				},
			},
			{
				id: 'piece_group_EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_.start - 0',
					end: '#piece_group_control_EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: 'EQg6irXwHuc2TMyqC_T4j7SvwsJlVtQY7SpwPEkekGHSQ_',
				},
				priority: 0,
			},
			{
				id: 'piece_group_control_EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'microphones',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: 'EQg6irXwHuc2TMyqC',
						pieceInstanceId: 'EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue',
						dynamicallyInserted: false,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['previous_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: 'EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue',
				},
			},
			{
				id: 'piece_group_EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue.start - 0',
					end: '#piece_group_control_EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: 'EQg6irXwHuc2TMyqC_bvsagXbL23DqH3SjbSSTcR_10LI__continue',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'part_group_2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4__infinite',
		objectType: 'rundown',
		enable: { start: 1740995399626 },
		priority: 1,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'microphones',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_NPnIomo9NZ75_oVFh5h5EA5lqb4_',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'part_group_2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue_infinite',
		objectType: 'rundown',
		enable: { start: 1740825479332 },
		priority: 1,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'dve_retain',
				priority: 2,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part', 'continues_infinite'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_qVY84uMxTImKLIarHRvbHPRnAaI__continue',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'part_group_2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue_infinite',
		objectType: 'rundown',
		enable: { start: 1740825043006 },
		priority: 1,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'PC1',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue',
						dynamicallyInserted: false,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part', 'continues_infinite'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [
					{
						id: '2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continuePnre0wszGD5MEPygEYSNtx1mZSM_',
						enable: { start: 0 },
						layer: 'vmix_audio_player_1',
						content: {
							deviceType: 'VMIX',
							type: 'INPUT',
							listFilePaths: ['N:\\\\audio/N/SIGN.wav'],
							playing: true,
						},
						priority: 1,
						objectType: 'rundown',
						originalId: 'Pnre0wszGD5MEPygEYSNtx1mZSM_',
					},
				],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_dDOhfM4He_w9Zpq20aAHjhQDd5o__continue',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'part_group_2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue_infinite',
		objectType: 'rundown',
		enable: { start: 1740825042686 },
		priority: 1,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'PC2',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue',
						dynamicallyInserted: false,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part', 'continues_infinite'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_QZZXwkt2Wl1Bf0r70vD_gvAfrfg__continue',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'part_group_2KDYWrf2pcRxMfag8',
		objectType: 'rundown',
		enable: { start: 1740995399626 },
		priority: 5,
		layer: '',
		content: { deviceType: 'ABSTRACT', type: 'group' },
		children: [
			{
				id: 'part_group_firstobject_2KDYWrf2pcRxMfag8',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'group_first_object',
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'partPlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
					},
					callBackStopped: 'partPlaybackStopped',
				},
				classes: [],
				priority: 0,
			},
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_',
				objectType: 'rundown',
				enable: { start: 0 },
				layer: 'cam',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [
					{
						id: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_iAR_SN_9gIe2qZZmrZz775cO8UQ_',
						priority: 1,
						enable: { start: 0 },
						layer: 'vmix_me_program',
						content: { deviceType: 'VMIX', type: 'PROGRAM', input: '1' },
						objectType: 'rundown',
						originalId: 'iAR_SN_9gIe2qZZmrZz775cO8UQ_',
					},
					{
						id: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sKGGjgpzTUZ6WEfgrptc0zGbD_E_',
						enable: { start: 0 },
						layer: 'vmix_faux_preview',
						content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: '1' } } },
						priority: 0,
						objectType: 'rundown',
						originalId: 'sKGGjgpzTUZ6WEfgrptc0zGbD_E_',
					},
					{
						id: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sa2PEDQ8N_isU22F4nkYjuCnz3U_',
						enable: { start: 0 },
						layer: 'vmix_mv_faux_preview',
						content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: '1' } } },
						priority: 0,
						objectType: 'rundown',
						originalId: 'sa2PEDQ8N_isU22F4nkYjuCnz3U_',
					},
				],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_',
				},
				priority: 0,
			},
			{
				id: 'piece_group_control_2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_',
				objectType: 'rundown',
				enable: { start: 0, duration: 0 },
				layer: 'dve_audio',
				priority: 5,
				content: {
					deviceType: 'ABSTRACT',
					type: 'callback',
					callBack: 'piecePlaybackStarted',
					callBackData: {
						rundownPlaylistId: 'ZPj6Z_MXsRPvxoSV6f6FDDGW81U_',
						partInstanceId: '2KDYWrf2pcRxMfag8',
						pieceInstanceId: '2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_',
						dynamicallyInserted: true,
					},
					callBackStopped: 'piecePlaybackStopped',
				},
				classes: ['current_part'],
				metaData: {
					isPieceTimeline: true,
					triggerPieceInstanceId: '2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_',
				},
			},
			{
				id: 'piece_group_2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_',
				content: { deviceType: 'ABSTRACT', type: 'group' },
				children: [],
				isGroup: true,
				objectType: 'rundown',
				enable: {
					start: '#piece_group_control_2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_.start - 0',
					end: '#piece_group_control_2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_.end + 0',
				},
				layer: '',
				metaData: {
					isPieceTimeline: true,
					pieceInstanceGroupId: '2KDYWrf2pcRxMfag8_rOhV1gTGOq8QHE5SN9eZDU5QLUw_',
				},
				priority: 0,
			},
		],
		isGroup: true,
		metaData: { isPieceTimeline: true },
	},
	{
		id: 'lookahead_timed0_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_iAR_SN_9gIe2qZZmrZz775cO8UQ_',
		priority: 0.1,
		enable: { start: 1, end: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_iAR_SN_9gIe2qZZmrZz775cO8UQ_.start' },
		layer: 'vmix_me_program',
		content: { deviceType: 'VMIX', type: 'PROGRAM', input: '1' },
		objectType: 'rundown',
		originalId: 'iAR_SN_9gIe2qZZmrZz775cO8UQ_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_XHIUde_I8YEP0yOGbnSHF3dRHHU_',
		priority: 0.05,
		enable: { start: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_iAR_SN_9gIe2qZZmrZz775cO8UQ_.start + 0' },
		layer: 'vmix_me_program',
		content: { deviceType: 'VMIX', type: 'PROGRAM', input: 46 },
		keyframes: [
			{
				id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_XHIUde_I8YEP0yOGbnSHF3dRHHU__keyframe_0',
				enable: { while: '1' },
				disabled: false,
				content: { input: '6' },
				preserveForLookahead: true,
				abSession: { poolName: 'clip', playerIndex: 0 },
			},
		],
		abSessions: [{ sessionName: 'N-INNTOLLTALL-220125-ELKES-NK#2', poolName: 'clip' }],
		objectType: 'rundown',
		originalId: 'XHIUde_I8YEP0yOGbnSHF3dRHHU_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_timed0_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sKGGjgpzTUZ6WEfgrptc0zGbD_E_',
		enable: { start: 1, end: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sKGGjgpzTUZ6WEfgrptc0zGbD_E_.start' },
		layer: 'vmix_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: '1' } } },
		priority: 0.1,
		objectType: 'rundown',
		originalId: 'sKGGjgpzTUZ6WEfgrptc0zGbD_E_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_4oxkq9FVef5zzGOpH826aTBmbQg_',
		enable: { start: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sKGGjgpzTUZ6WEfgrptc0zGbD_E_.start + 0' },
		layer: 'vmix_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
		keyframes: [
			{
				id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_4oxkq9FVef5zzGOpH826aTBmbQg__keyframe_0',
				enable: { while: '1' },
				disabled: false,
				content: { layers: { '1': { input: '6' } } },
				preserveForLookahead: true,
				abSession: { poolName: 'clip', playerIndex: 0 },
			},
		],
		abSessions: [{ sessionName: 'N-INNTOLLTALL-220125-ELKES-NK#2', poolName: 'clip' }],
		priority: 0.05,
		objectType: 'rundown',
		originalId: '4oxkq9FVef5zzGOpH826aTBmbQg_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_timed0_2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sa2PEDQ8N_isU22F4nkYjuCnz3U_',
		enable: { start: 1, end: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sa2PEDQ8N_isU22F4nkYjuCnz3U_.start' },
		layer: 'vmix_mv_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: '1' } } },
		priority: 0.1,
		objectType: 'rundown',
		originalId: 'sa2PEDQ8N_isU22F4nkYjuCnz3U_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_A8_3MnrKLZqshqrnbiXv0gz7UV8_',
		enable: { start: '#2KDYWrf2pcRxMfag8_febE_Q717ptI5nZqYlvyEfrzFFY_sa2PEDQ8N_isU22F4nkYjuCnz3U_.start + 0' },
		layer: 'vmix_mv_faux_preview',
		content: { deviceType: 'VMIX', type: 'INPUT', layers: { '1': { input: 46 } } },
		keyframes: [
			{
				id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_A8_3MnrKLZqshqrnbiXv0gz7UV8__keyframe_0',
				enable: { while: '1' },
				disabled: false,
				content: { layers: { '1': { input: '6' } } },
				preserveForLookahead: true,
				abSession: { poolName: 'clip', playerIndex: 0 },
			},
		],
		abSessions: [{ sessionName: 'N-INNTOLLTALL-220125-ELKES-NK#2', poolName: 'clip' }],
		priority: 0.05,
		objectType: 'rundown',
		originalId: 'A8_3MnrKLZqshqrnbiXv0gz7UV8_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_DIuYJVPX0f24iUroJpK_LQJl0Zo_oPO36PWo_rhicGlqX2UadRpyUaY_',
		enable: { while: '1' },
		layer: 'vmix_fullscreen_graphics_preview_input',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			url: 'https://kdisk.tv2asa.no/arkiv/vcpcroptooloutput2023/crop_branntomtandoya.png',
		},
		priority: 0.05,
		objectType: 'rundown',
		originalId: 'oPO36PWo_rhicGlqX2UadRpyUaY_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_YUFfpyvmwh4oOzEA1xAAbh3Pdc8__9hLoEScRpMCxsxGHH_t0GIuDFOkCMoHm4XYof4gJWK7Ec_J_BxHBV4BQ0ePVWmBwPGXLzluJE_',
		enable: { while: '1' },
		priority: 0.05,
		layer: 'vmix_clip_player_0',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			listFilePaths: ['N:\\\\clips\\\\N-INNTOLLTALL-220125-ELKES-NK#2.mp4'],
			playing: false,
			restart: true,
			seek: -3922,
		},
		keyframes: [],
		abSessions: [{ sessionName: 'N-INNTOLLTALL-220125-ELKES-NK#2', poolName: 'clip' }],
		objectType: 'rundown',
		originalId: 'J_BxHBV4BQ0ePVWmBwPGXLzluJE_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: 'lookahead_future0_8O_mtxNU0kCCrgZmthU_55xWx5k_FmWP1eJP5k4TW4bv0W2Yw0jBnhI_',
		priority: 0.05,
		enable: { while: '1' },
		layer: 'vmix_dve_1',
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: '31', panX: 0, panY: 0, zoom: 1, cropLeft: 0, cropTop: 0, cropRight: 1, cropBottom: 1 },
				'2': {
					input: 1,
					panX: -0.5026041,
					panY: 0.1240855,
					zoom: 0.4973958,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
				},
				'3': {
					input: 2,
					panX: 0.5026042,
					panY: 0.1240855,
					zoom: 0.4973958,
					cropLeft: 0,
					cropTop: 0,
					cropRight: 1,
					cropBottom: 1,
				},
			},
		},
		abSessions: [{ poolName: 'dve', sessionName: 'Butterfly' }],
		objectType: 'rundown',
		originalId: 'FmWP1eJP5k4TW4bv0W2Yw0jBnhI_',
		isLookahead: true,
		disabled: false,
	},
	{
		id: '7oK5p8JjaFoOysG16wCkXYcleAQ__keepalive',
		enable: { start: '#7oK5p8JjaFoOysG16wCkXYcleAQ_.end', duration: 320 },
		priority: 0.2,
		content: { deviceType: 'VMIX', type: 'INPUT', loop: true, playing: true },
		layer: 'vmix_dve_bg',
		objectType: 'rundown',
	},
	{
		id: 'T7lg735NryDF9ojCG_KzKGF5K2c__keepalive',
		enable: { start: '#T7lg735NryDF9ojCG_KzKGF5K2c_.end', duration: 320 },
		priority: 0.2,
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: 31 },
				'2': { input: 45 },
				'3': { input: 45 },
				'4': { input: 45 },
				'5': { input: 45 },
			},
		},
		layer: 'vmix_dve_1',
		objectType: 'rundown',
	},
	{
		id: 'PfOeLatcKbdyTiBUGhPciu8Vfos__keepalive',
		enable: { start: '#PfOeLatcKbdyTiBUGhPciu8Vfos_.end', duration: 320 },
		priority: 0.2,
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: 31 },
				'2': { input: 45 },
				'3': { input: 45 },
				'4': { input: 45 },
				'5': { input: 45 },
			},
		},
		layer: 'vmix_dve_2',
		objectType: 'rundown',
	},
	{
		id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_F669L65bjFMMWnOtYlkSOXXmjN4__keepalive',
		enable: {
			start: '#EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_F669L65bjFMMWnOtYlkSOXXmjN4_.end',
			duration: 320,
		},
		priority: 0.2,
		content: {
			deviceType: 'VMIX',
			type: 'INPUT',
			layers: {
				'1': { input: '31', panX: 0, panY: 0, zoom: 1, cropLeft: 0, cropTop: 0, cropRight: 1, cropBottom: 1 },
				'2': {
					input: 2,
					panX: -0.673,
					panY: 0,
					zoom: 0.4,
					cropLeft: 0.1042,
					cropTop: 0,
					cropRight: 0.8958,
					cropBottom: 1,
				},
				'3': {
					input: 1,
					panX: 0,
					panY: 0,
					zoom: 0.4,
					cropLeft: 0.1042,
					cropTop: 0,
					cropRight: 0.8958,
					cropBottom: 1,
				},
				'4': {
					input: 62,
					panX: 0.673,
					panY: 0,
					zoom: 0.4,
					cropLeft: 0.1042,
					cropTop: 0,
					cropRight: 0.8958,
					cropBottom: 1,
				},
			},
		},
		layer: 'vmix_dve_2',
		objectType: 'rundown',
	},
	{
		id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sM5pn9UiPZf6kWNwDKXLKWckdaQ__keepalive',
		enable: {
			start: '#EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sM5pn9UiPZf6kWNwDKXLKWckdaQ_.end',
			duration: 320,
		},
		priority: 0.2,
		content: { type: 'INPUT', deviceType: 'VMIX' },
		layer: 'vmix_dve_labels_1',
		keyframes: [
			{
				id: 'sM5pn9UiPZf6kWNwDKXLKWckdaQ__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sM5pn9UiPZf6kWNwDKXLKWckdaQ__keepalive',
				enable: { while: '1' },
				disabled: false,
				abSession: { poolName: 'dve', playerIndex: 1 },
				content: { layers: {} },
				preserveForLookahead: true,
			},
		],
		objectType: 'rundown',
	},
	{
		id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sWPFgU5TaBJMk4qIgp4YcxM4guo__keepalive',
		enable: {
			start: '#EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sWPFgU5TaBJMk4qIgp4YcxM4guo_.end',
			duration: 320,
		},
		priority: 0.2,
		content: { type: 'INPUT', deviceType: 'VMIX' },
		layer: 'vmix_dve_labels_1',
		keyframes: [
			{
				id: 'sWPFgU5TaBJMk4qIgp4YcxM4guo__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_sWPFgU5TaBJMk4qIgp4YcxM4guo__keepalive',
				enable: { while: '1' },
				disabled: false,
				abSession: { poolName: 'dve', playerIndex: 1 },
				content: { layers: {} },
				preserveForLookahead: true,
			},
		],
		objectType: 'rundown',
	},
	{
		id: 'EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_j9xIsiJjovQ4n2Z2BHVpzJZJDL4__keepalive',
		enable: {
			start: '#EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_j9xIsiJjovQ4n2Z2BHVpzJZJDL4_.end',
			duration: 320,
		},
		priority: 0.2,
		content: { type: 'INPUT', deviceType: 'VMIX' },
		layer: 'vmix_dve_labels_1',
		keyframes: [
			{
				id: 'j9xIsiJjovQ4n2Z2BHVpzJZJDL4__keyframe_1_EQg6irXwHuc2TMyqC_1luGKczWX3Rd2zA7Thn_RpxPBgA_j9xIsiJjovQ4n2Z2BHVpzJZJDL4__keepalive',
				enable: { while: '1' },
				disabled: false,
				abSession: { poolName: 'dve', playerIndex: 1 },
				content: { layers: {} },
				preserveForLookahead: true,
			},
		],
		objectType: 'rundown',
	},
]
